### PR TITLE
[Propose] Customize StdoutOutputPlugin to use formatter

### PR DESCRIPTION
**Pull request by sonots**
What I expected for StdoutOutputPlugin was to output the formatted results.
So, I customized StdoutOutputPlugin to use formatter. 

If we want to see the internal states of embulk records, we can now use [embulk-filter-stdout](https://github.com/sonots/embulk-filter-stdout).

### CODE REVIEW

**Comment by sonots** [comment]
I wanted to set the default formatter as

```
filter:
  type: csv
  quote_policy: NONE
```

as the output will be similar with the original behavior, but I could not find a good simple way to do it. Any idea?

**Comment by frsyuki** [comment]
I used OutputPlugin because it's easy to use.

```
out:
  type: stdout
```

vs

```
out:
  type: stdout
  formatter:
    type: csv
```

I think stdout should be kept as-is to provide above simplicity.
How about creating another plugin like `stdout_file`?

**Comment by sonots** [comment]
I want to make the default behavior to be `formmatter: csv` so that we can write as:

```
out:
  type: stdout
```

If this is possible, I think `stdout_file` is not necessary, and we can avoid the wierd name plugin > `stdout_file`.

**Comment by frsyuki** [comment]
That makes sense. And I agree that. But we can't do that because of plugin API design.
FileOutputPlugin is wrapped in FileOutputRunner. So, FileOutputPlugin is not a OutputPlugin. This was necessary to make Java plugin API easy to use. But because of this, FileOutputPlugin can't modify or generate configuration for FormatterPlugin.

**Comment by sonots** [comment]
Hmm

**Comment by dmikurube** [comment]
Sorry that this pull request has been left. Let us close this pull request.

**Pull request closed without merging**
