### PR TITLE
Add JarPluginLoader to load a JAR-based plugin class.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Next to #686, implementing a class that actually loads a JAR-based plugin class. #684 will be after this PR.

Order: #686 ==> This (#687) ==> #684

### CODE REVIEW

**Comment by dmikurube** [comment]
`JarPluginLoader` has no test code yet atm. We'd need some example JAR files in `src/test/resources` to test it.

**Comment by muga** [comment]
@dmikurube The main code looks good to me 👍  Can I ask you to add unit tests for this feature?

**Comment by dmikurube** [comment]
Yes, to be adding.

**Comment by dmikurube** [comment]
@muga Added a test which builds a JAR file and loads using `JarPluginLoader`.

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
