### PR TITLE
Un-JRuby the "migrate" subcommand.

### PR DESCRIPTION
**Pull request by dmikurube**
Not tested very well, though...

### CODE REVIEW

**Comment by dmikurube** [comment]
@muga Catching up with Java-based VERSION. Unlike others this is complicated. It may need some tests...

**Comment by muga** [comment]
@dmikurube The implementation looks good to me. If you could take a time to test it, it would be great. 👍

**Comment by dmikurube** [comment]
Okay. I guess it's difficult to have test code, but I'd have some manual testing on it.

**Comment by dmikurube** [comment]
Rebased e7984a3 onto `master` as ca19788.

**Comment by dmikurube** [comment]
@muga Tested, and it was not working very fine (as expected!).

Fixed in 83ccfe9. Tested with vanilla Java & Ruby plugins created by `embulk-0.6.27.jar new {java|ruby}-input`.

**Comment by dmikurube** [comment]
Thanks! Merging.

**Pull request merged**
