### PR TITLE
[WIP] Introduce binary type

### PR DESCRIPTION
**Pull request by tomykaira**
This approaches #420.

The largest problem is that many plugins will be not compatible when this new type is introduced.

I would like to discuss how the binary type should behave, and how to merge this into mainline. Thanks, all.

### CODE REVIEW

**Comment by dallin** [comment]
Really looking forward to this feature being added.

**Comment by tomykaira** [comment]
I cannot commit to this feature any more. I really appreciate if someone take over to be merged!

**Comment by muga** [comment]
To avoid unexpected LinkageError, we should upgrade Java8 before binary type support.

**Comment by dmikurube** [comment]
We're going to introduce Binary type in v0.9, which is expected to be released in a couple of months.

Thanks to this PR, the first implementation would be easy. But I'm afraid we may be going to make another PR to introduce Binary type since:

* It's conflicting with the current `master` at Git's level. (It's because we took much time to do it. Sorry about that.)
* Some interfaces have been changed in Embulk. (Ditto. Sorry.)
* We'd use another class for Binary (`java.nio.ByteBuffer` or Embulk's own class), instead of `byte[]`. (`byte[]` is not very good to use there -- it's mutable, and too primitive.)

Let me take this opportunity to appreciate @tomykaira 's effort on this. Thanks for your contribution!

**Comment by dmikurube** [comment]
New commits to be made in #850.

**Pull request closed without merging**
