### PR TITLE
TimeStamp.fromString should be public

### PR DESCRIPTION
**Pull request by xerial**
Plugin needs to access this method to create Timestamp from strings.

### CODE REVIEW

**Comment by frsyuki** [comment]
In which case you need `Timestamp.fromString`? Why don't you use TimestampParser?

**Comment by xerial** [comment]
I failed to notice there is TimestampParser.

**Comment by xerial** [comment]
My expectation was there is some factory method like `Integer.parseInt(str)'

**Comment by xerial** [comment]
What is the difference of `Timestamp.fromString` and `TimestampParser

**Pull request closed without merging**
