### PR TITLE
Un-JRuby the "new" subcommand.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga The "new" subcommand is ready in Java.

### CODE REVIEW

**Comment by dmikurube** [comment]
@muga Catching up with the Java-based VERSION, and getting ready. Can you PTAL?

**Comment by hiroyuki-sato** [comment]
@dmikurube

Thank you for great work.

I compared the latest version (v0.8.18) and java-embulk-new(eb69d245665b5eeca127e8cf484f1f5c6366029a) branch
There are following differences.

* `-`: latest version (v0.8.18)
* `+`: java-embulk-new(eb69d245665b5eeca127e8cf484f1f5c6366029a) branch

## Summaries.

* Missing Section part in README.md.

```diff
-## Overview
```

* Un-Jruby version has extra whitespace.
* Wrong classname It contains `replace("Plugin", "GuessPlugin")`.

```diff
-    #class TestRubyParser < TextGuessPlugin
-    #  Plugin.register_guess("test_ruby_parser", self)
+    # class TestRubyParser.replace("Plugin", "GuessPlugin") < TextGuessPlugin
+    #   Plugin.register_guess("test_ruby_parser", self)
```

* Need to remove `%>`

```diff
-    #require "embulk/parser/test_ruby_parser.rb"
+    # require "embulk/parser/test_ruby_parser.rb" %>
```

## complete diff

    diff -ur v0.8.18/embulk-parser-test_ruby_parser java-embulk-new/embulk-parser-test_ruby_parser
    diff -ur v0.8.18/embulk-parser-test_ruby_parser/README.md java-embulk-new/embulk-parser-test_ruby_parser/README.md
    --- v0.8.18/embulk-parser-test_ruby_parser/README.md	2017-04-12 16:12:35.000000000 +0900
    +++ java-embulk-new/embulk-parser-test_ruby_parser/README.md	2017-04-12 16:15:10.000000000 +0900
    @@ -2,18 +2,15 @@

     TODO: Write short description here and embulk-parser-test_ruby_parser.gemspec file.

    -## Overview

     * **Plugin type**: parser
     * **Guess supported**: no

    -## Configuration

     - **option1**: description (integer, required)
     - **option2**: description (string, default: `"myvalue"`)
     - **option3**: description (string, default: `null`)

    -## Example

     ```yaml
     in:
    @@ -31,7 +28,6 @@
     $ embulk guess -g test_ruby_parser config.yml -o guessed.yml
     ```

    -## Build

     ```
     $ rake
    diff -ur v0.8.18/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb java-embulk-new/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb
    --- v0.8.18/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb	2017-04-12 16:12:35.000000000 +0900
    +++ java-embulk-new/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb	2017-04-12 16:15:10.000000000 +0900
    @@ -8,56 +8,56 @@
         #      one of binary guess (GuessPlugin), text guess (TextGuessPlugin),
         #      or line guess (LineGuessPlugin).

    -    #require "embulk/parser/test_ruby_parser.rb"
    +    # require "embulk/parser/test_ruby_parser.rb" %>

    -    #class TestRubyParser < GuessPlugin
    -    #  Plugin.register_guess("test_ruby_parser", self)
    +    # class TestRubyParser.replace("Plugin", "GuessPlugin") < GuessPlugin
    +    #   Plugin.register_guess("test_ruby_parser", self)
         #
    -    #  def guess(config, sample_buffer)
    -    #    if sample_buffer[0,2] == GZIP_HEADER
    -    #      guessed = {}
    -    #      guessed["type"] = "test_ruby_parser"
    -    #      guessed["property1"] = "guessed-value"
    -    #      return {"parser" => guessed}
    -    #    else
    -    #      return {}
    -    #    end
    -    #  end
    -    #end
    +    #   def guess(config, sample_buffer)
    +    #     if sample_buffer[0,2] == GZIP_HEADER
    +    #       guessed = {}
    +    #       guessed["type"] = "test_ruby_parser"
    +    #       guessed["property1"] = "guessed-value"
    +    #       return {"parser" => guessed}
    +    #     else
    +    #       return {}
    +    #     end
    +    #   end
    +    # end

    -    #class TestRubyParser < TextGuessPlugin
    -    #  Plugin.register_guess("test_ruby_parser", self)
    +    # class TestRubyParser.replace("Plugin", "GuessPlugin") < TextGuessPlugin
    +    #   Plugin.register_guess("test_ruby_parser", self)
         #
    -    #  def guess_text(config, sample_text)
    -    #    js = JSON.parse(sample_text) rescue nil
    -    #    if js && js["mykeyword"] == "keyword"
    -    #      guessed = {}
    -    #      guessed["type"] = "test_ruby_parser"
    -    #      guessed["property1"] = "guessed-value"
    -    #      return {"parser" => guessed}
    -    #    else
    -    #      return {}
    -    #    end
    -    #  end
    -    #end
    +    #   def guess_text(config, sample_text)
    +    #     js = JSON.parse(sample_text) rescue nil
    +    #     if js && js["mykeyword"] == "keyword"
    +    #       guessed = {}
    +    #       guessed["type"] = "test_ruby_parser"
    +    #       guessed["property1"] = "guessed-value"
    +    #       return {"parser" => guessed}
    +    #     else
    +    #       return {}
    +    #     end
    +    #   end
    +    # end

    -    #class TestRubyParser < LineGuessPlugin
    -    #  Plugin.register_guess("test_ruby_parser", self)
    +    # class TestRubyParser.replace("Plugin", "GuessPlugin") < LineGuessPlugin
    +    #   Plugin.register_guess("test_ruby_parser", self)
         #
    -    #  def guess_lines(config, sample_lines)
    -    #    all_line_matched = sample_lines.all? do |line|
    -    #      line =~ /mypattern/
    -    #    end
    -    #    if all_line_matched
    -    #      guessed = {}
    -    #      guessed["type"] = "test_ruby_parser"
    -    #      guessed["property1"] = "guessed-value"
    -    #      return {"parser" => guessed}
    -    #    else
    -    #      return {}
    -    #    end
    -    #  end
    -    #end
    +    #   def guess_lines(config, sample_lines)
    +    #     all_line_matched = sample_lines.all? do |line|
    +    #       line =~ /mypattern/
    +    #     end
    +    #     if all_line_matched
    +    #       guessed = {}
    +    #       guessed["type"] = "test_ruby_parser"
    +    #       guessed["property1"] = "guessed-value"
    +    #       return {"parser" => guessed}
    +    #     else
    +    #       return {}
    +    #     end
    +    #   end
    +    # end

       end
     end

**Comment by dmikurube** [comment]
@hiroyuki-sato Thanks for confirmation!

> Missing Section part in README.md.

I was unaware that `##` are commented out in Velocity. Fixed.

> Un-Jruby version has extra whitespace.

Do you mean some `#` are converted into `# `? It's intentional if so.

> Wrong classname It contains `replace("Plugin", "GuessPlugin")`.
> Need to remove `%>`

Good catches! Thanks!

**Comment by hiroyuki-sato** [comment]
In short, LGTM! 👍 

* `-`: Latest version (v0.8.18)
* `+`: c02aa74d1f1a4e65accf1c832b7b1f170572d4ad

## Compare plugins with `--ignore-all-space`

```
% diff -wur test/v0.8.18/embulk-parser-test_ruby_parser test/java-embulk-new/embulk-parser-test_ruby_parser
%
```

No difference output (Completely same result.(except space))

## Checked plugins.

```
embulk-decoder-test_java_decoder
embulk-encoder-test_java_encoder
embulk-filter-test_java_filter
embulk-filter-test_ruby_filter
embulk-formatter-test_java_formatter
embulk-formatter-test_ruby_formatter
embulk-input-test_java_file_input
embulk-input-test_java_input
embulk-input-test_ruby_input
embulk-output-test_java_file_output
embulk-output-test_java_output
embulk-output-test_ruby_output
embulk-parser-test_java_parser
embulk-parser-test_ruby_parser
```


## Compare plugins without `--ignore-all-space` 


```diff
diff -ur test/v0.8.18/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb test/java-embulk-new/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb
--- test/v0.8.18/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb	2017-04-12 16:12:35.000000000 +0900
+++ test/java-embulk-new/embulk-parser-test_ruby_parser/lib/embulk/guess/test_ruby_parser.rb	2017-04-14 17:33:19.000000000 +0900
@@ -8,56 +8,56 @@
     #      one of binary guess (GuessPlugin), text guess (TextGuessPlugin),
     #      or line guess (LineGuessPlugin).
 
-    #require "embulk/parser/test_ruby_parser.rb"
+    # require "embulk/parser/test_ruby_parser.rb"
 
-    #class TestRubyParser < GuessPlugin
-    #  Plugin.register_guess("test_ruby_parser", self)
+    # class TestRubyParser < GuessPlugin
+    #   Plugin.register_guess("test_ruby_parser", self)
     #
-    #  def guess(config, sample_buffer)
-    #    if sample_buffer[0,2] == GZIP_HEADER
-    #      guessed = {}
-    #      guessed["type"] = "test_ruby_parser"
-    #      guessed["property1"] = "guessed-value"
-    #      return {"parser" => guessed}
-    #    else
-    #      return {}
-    #    end
-    #  end
-    #end
+    #   def guess(config, sample_buffer)
+    #     if sample_buffer[0,2] == GZIP_HEADER
+    #       guessed = {}
+    #       guessed["type"] = "test_ruby_parser"
+    #       guessed["property1"] = "guessed-value"
+    #       return {"parser" => guessed}
+    #     else
+    #       return {}
+    #     end
+    #   end
+    # end
 
-    #class TestRubyParser < TextGuessPlugin
-    #  Plugin.register_guess("test_ruby_parser", self)
+    # class TestRubyParser < TextGuessPlugin
+    #   Plugin.register_guess("test_ruby_parser", self)
     #
-    #  def guess_text(config, sample_text)
-    #    js = JSON.parse(sample_text) rescue nil
-    #    if js && js["mykeyword"] == "keyword"
-    #      guessed = {}
-    #      guessed["type"] = "test_ruby_parser"
-    #      guessed["property1"] = "guessed-value"
-    #      return {"parser" => guessed}
-    #    else
-    #      return {}
-    #    end
-    #  end
-    #end
+    #   def guess_text(config, sample_text)
+    #     js = JSON.parse(sample_text) rescue nil
+    #     if js && js["mykeyword"] == "keyword"
+    #       guessed = {}
+    #       guessed["type"] = "test_ruby_parser"
+    #       guessed["property1"] = "guessed-value"
+    #       return {"parser" => guessed}
+    #     else
+    #       return {}
+    #     end
+    #   end
+    # end
 
-    #class TestRubyParser < LineGuessPlugin
-    #  Plugin.register_guess("test_ruby_parser", self)
+    # class TestRubyParser < LineGuessPlugin
+    #   Plugin.register_guess("test_ruby_parser", self)
     #
-    #  def guess_lines(config, sample_lines)
-    #    all_line_matched = sample_lines.all? do |line|
-    #      line =~ /mypattern/
-    #    end
-    #    if all_line_matched
-    #      guessed = {}
-    #      guessed["type"] = "test_ruby_parser"
-    #      guessed["property1"] = "guessed-value"
-    #      return {"parser" => guessed}
-    #    else
-    #      return {}
-    #    end
-    #  end
-    #end
+    #   def guess_lines(config, sample_lines)
+    #     all_line_matched = sample_lines.all? do |line|
+    #       line =~ /mypattern/
+    #     end
+    #     if all_line_matched
+    #       guessed = {}
+    #       guessed["type"] = "test_ruby_parser"
+    #       guessed["property1"] = "guessed-value"
+    #       return {"parser" => guessed}
+    #     else
+    #       return {}
+    #     end
+    #   end
+    # end
 
   end
 end
```

**Comment by dmikurube** [comment]
Thanks. Merging.

**Pull request merged**
