### PR TITLE
[WIP] Update gradle 4.0 

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Let's update Gradle to version 4.X in the near future. 
It seems that build speed faster than 3.X.
And `gradlew cli` worked well. 

| version | gradlew cli build speed |
|------|---------|
| 3.2.1 | 42sec |
| 4.0.0 | 21sec |

* Priority: low.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
The `embulk migrate` command also update Gradle version.

The `embulk migrate` command additionally replace `gradlew` file.
This script file differs between current(4.0) and previous(3.2.1).
The `gradlew` file needs to set executable permission. 
I'll fix this after #702 merged. It needs `setExecutable` method.

**Comment by hiroyuki-sato** [comment]
`embulk migrate` now update gradle to 4.0.

I want to care this warning. 

```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
```

**Comment by hiroyuki-sato** [comment]
How about adding a message like the below?

### Append message

If you see the following message during build a plugin, you need to rewrite build.gradle.
"The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead."
Please see this url 'http://xxx.xxx.xx/' for more detail


## page content

> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

The following methods has been deprecated.

```
// WRONG: Description assigned in execution phase
task helloWorld << {
    description = 'Prints out a message.'
    println 'Hello world!'
}
```

You need rewrite like the below. 

```
// CORRECT: Description assigned in configuration phase
task helloWorld {
    description = 'Prints out a message.'
    doLast {
        println 'Hello world!'
    }
}
```

Please see more detail about this change.
[The left shift operator on the Task interface](https://docs.gradle.org/3.2/release-notes.html#the-left-shift-operator-on-the-task-interface)

**Comment by hiroyuki-sato** [comment]
Add a caution message. 

```
Detected Java plugin for Embulk 0.8.15...


** CAUTION **

If you see this message, you need to modify build.gradle.
Please see more detail at this URL: https://github.com/embulk/embulk/pull/698#issuecomment-312422241

"The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead."


Done. Please check modified files.
```

**Comment by dmikurube** [comment]
@hiroyuki-sato Thanks for the contribution. To be honest, this PR looks mixing so many issues, not just upgrading the core to Gradle 4.0, but also executable flags, plugin's default, and a caution message.

At least upgrading the core to Gradle 4.0 should be an independent PR to avoid confusion by the changes. Can you split them?

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for reviewing.

I'll separate into three PRs.
* Add an `executable` flag for Migrator.
* Update Gradle 4.0
* Add `Task.leftShift(Closure)` warning.

**Comment by hiroyuki-sato** [comment]
I close this PR. Split into multiple PRs.
The first PR is #710

**Pull request closed without merging**
