### PR TITLE
Release v0.8.23

### PR DESCRIPTION
**Pull request by dmikurube**
@sakama Can you have a look?  (Cc: @muga)

Plan: #662

### CODE REVIEW

**Comment by dmikurube** [comment]
Merged all PRs planned. Will release (when my Bintray account is ready ;) ).

**Comment by dmikurube** [comment]
@muga I now have access on bintray.com/embulk. To release a new version, does just `./gradlew release` work? (I'd run that with Java 7.)

**Comment by dmikurube** [comment]
Updated the date again.

**Comment by muga** [comment]
ready to release 👍

**Comment by dmikurube** [comment]
CI got happy. Releasing v0.8.23. :)

**Comment by dmikurube** [comment]
Released v0.8.23:

- https://bintray.com/embulk/maven/embulk/0.8.23
- https://rubygems.org/gems/embulk/versions/0.8.23
- https://github.com/embulk/embulk/releases/tag/v0.8.23

**Pull request merged**
