### PR TITLE
selfrun.sh: Added argument ERRORLEVEL to exit/b after java command

### PR DESCRIPTION
**Pull request by hishidama**
For execute on Cygwin, return java command exit code.

### CODE REVIEW

**Comment by frsyuki** [comment]
Honestly speaking, I have no ideas about this script on Windows.
So, I'll just merge and hope it works well.

**Comment by hito4t** [comment]
I've built and run it.
It works well both in Windows command line and in Cygwin.

**Comment by frsyuki** [comment]
:+1:

**Comment by cosmo0920** [comment]
:+1:

**Pull request merged**
