### PR TITLE
Avoid IllegalArgumentException in try-with-resource

### PR DESCRIPTION
**Pull request by hata**
When using try-with-resource block and throw Exception in both the block
and close() method, `IllegalArgumentException: Self-suppression not
permitted` is thrown. LocalExecutorPlugin throws the exception when
OutputPlugin throws RuntimeException. RuntimeException is caught by
ExecutorService and the result is returned via Future object in
OutputWorkers. When OutputPlugin throws RuntimeException, Future.get()
throws ExecutionException. The exception is handled by
ScatterTransactionalPageOutput.completeWorkers(). completeWorkers()
are called by finish(), close(), commit(), and abort().
When finish()(or commit()) throws RuntimeException via completeWorkers(),
close()(and abort() via AbortTransactionResource) also throws
RuntimeException. From this, IAE is thrown.

This fix is to store a first RuntimeException as reportedException and
then check it in close() or abort() to avoid throwing the same exception
again.

I think this code may fix Issue #415 although I didn't test it using the same plugin.

### CODE REVIEW

**Comment by hata** [comment]
FYI:
In my local environment, I could see the same failures using `./gradlew rubyTest` command. And my change only relates to handling RuntimeException. So, I guess the failure comes from another change.

**Comment by hata** [comment]
FYI: I filed a new issue #439 and commented the first failure commit.

**Comment by frsyuki** [comment]
Isn't the root cause `completeWorkers()` throwing the same exception twice?
`ScatterTransactionalPageOutput.close` should not throw RuntimeException when `ScatterTransactionalPageOutput.finish` (or commit or abort)` throw an exception. How do you think with #446?

**Comment by hata** [comment]
@frsyuki You are correct and Your fix looks very good. I will close this request because your fix is good enough to me :)

**Pull request closed without merging**
