### PR TITLE
[Doc] add document of #651

### PR DESCRIPTION
**Pull request by smdmts**
add the parameter option documents for #651.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@smdmts Thank you for writing the document. 

Can you add the following document? I would like to know more detail about `invalid_string_escape`
behavior. 

Especially `invaild_string_escape` `PASTHROUGH` and `stop_invalid_record` is `false`

### example

The `\a` is the invalid string. The `invalid_string_escapes` behave like the below.

| invalid_string_escapes | result         |
|------------------------|----------------|
| PASSTHROUGH*1          | \a             | 
| SKIP                   | empty string   |
| UNESCAPE               | a              |

*1 Raise an exception and stop parsing if `stop_on_invalid` if `true`.

**Comment by smdmts** [comment]
@hiroyuki-sato I got it, and fix soon.

**Comment by smdmts** [comment]
@hiroyuki-sato I fix it!

**Comment by smdmts** [comment]
@hiroyuki-sato I fixed it!

**Comment by hiroyuki-sato** [comment]
@smdmts Thank you!.

Please fix the following

The example json file is invalid. 
The value of `name` unquote. 
second record `name` is missing. 

```
{"time":1455829282,"ip":"93.184.216.34","name":"frsyuki"}
{"time":1455829282,"ip":"172.36.8.109", "name":"sadayuki"}
{"time":1455829284,"ip":"example.com","name":"Treasure Data"}
{"time":1455829282,"ip":"10.98.43.1","name":"MessagePack"}
```

By the way, 

~~If input data is below string. (It contains `\a`)~~
~~And `invalid_string_escape` is `PASSTHROUGH`.~~

~~Raise an exception even `stop_on_invalid` is false.~~
~~So *1 part should fix.  ~~
~~ What do you think?~~

**You already fix this before I submit the comments.**

```
{"time":1455829282,"ip":"93.184.216.34","name":"frsyuki\a"}
```

**Comment by hiroyuki-sato** [comment]
Oh! Sorry JSON data already are broken before you create PR.
I'll create another PR. 

LGTM.
@dmikurube , @muga Please take a look when you can.

**Comment by muga** [comment]
Merging. Thank you.

**Pull request merged**
