### PR TITLE
Release v0.8.34

### PR DESCRIPTION
**Pull request by dmikurube**
@muga @sakama v0.8.34 will be released only with #791.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
What do you think to add the releate note the following message?

```
This release contains some secuirty fixes in builtin rubygems. http://blog.rubygems.org/2017/08/27/2.6.13-released.html
```

**Comment by dmikurube** [comment]
@hiroyuki-sato Thought about that, but I think we don't need that in this Embulk's release note.

**Comment by dmikurube** [comment]
Just waiting for one more day to hear about 0.8.33. To release tomorrow...

**Comment by hiroyuki-sato** [comment]
@dmikurube OK, Thanks!

**Comment by dmikurube** [comment]
Merging...

**Pull request merged**
