### PR TITLE
fix typo annoucement -> announcement

### PR DESCRIPTION
**Pull request by hiroyuki-sato**

### CODE REVIEW

**Comment by dmikurube** [comment]
@hiroyuki-sato Thanks! But sorry, it was conflicting with #926. Let us do this in #926.

Jfyi, please check CONTRIBUTING.md we've recently introduced. Just filing an issue is usually fine for this kind of fixes.
https://raw.githubusercontent.com/embulk/embulk/master/.github/CONTRIBUTING.md

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for the comment.
I created the issue #927. 

Will you add this change in #926?. 
If so, I'll close this PR and #927 after #926 merged. 

If not, I'll fix the conflict after #926 merged.

**Comment by dmikurube** [comment]
Thanks! Yes, it's done at https://github.com/embulk/embulk/pull/926/files#diff-e473dca3fac20771e6b73f152bdf8bddR682.

**Comment by hiroyuki-sato** [comment]
Thanks!. I close this PR.

**Pull request closed without merging**
