### PR TITLE
Add an option to change page buffer size with -J-Dembulk.pageSize=N

### PR DESCRIPTION
**Pull request by sonots**
Fix https://github.com/embulk/embulk/issues/246

I verified this patch worked well with embulk-output-vertica. 
Please let me know if there is a way to write a test.

### CODE REVIEW

**Comment by sonots** [comment]
circleci failed, but seems not related with this commit?

**Comment by frsyuki** [comment]
Please just ignore CircleCI. I deleted embulk from CircleCI.

**Comment by frsyuki** [comment]
I think you can test using Injector.
`org.embulk.EmbulkTestRuntime` gives you sets of test utilities.

To get BufferAllocator, this code should work:

``
BufferAllocator = new EmbulkTestRuntime().getInstance(BufferAllocator.class)`
``

To set some system config, you can override `EmbulkTestRuntime.getSystemConfig() as following:`

``
BufferAllocator = new EmbulkTestRuntime()
{
    protected ConfigSource getSystemConfig()
    {
        super.getSystemConfig().set("pageSize", 123456789);
    }
}.getInstance(BufferAllocator.class)`
``

**Comment by frsyuki** [comment]
I merged current commits so far. I welcome adding tests! Thank you

**Comment by sonots** [comment]
Thanks!

**Comment by frsyuki** [comment]
I think "kb" can be a pitfall. Supporting units such as "pageSize=10KB" or "pageSize=1MB" makes more sense. org.embulk.spi.unit.ByteSize provides it. Once it's implemented, I'll release new version.

**Comment by frsyuki** [comment]
@sonots I added 2 follow-up commits:

* pageSize config accepts units such as KB or MB: https://github.com/embulk/embulk/commit/bf7ed52057cfbc7929ae03f3779abdd7b5e4db66
* `embulk run` accepts `-X key=value` cmdline argument to set pageSize: https://github.com/embulk/embulk/commit/5f646cc51a4585e4d09a1df64a3aa3a113bc18ba

**Comment by sonots** [comment]
:+1: Thanks!

**Comment by frsyuki** [comment]
I found that system config should be camel case (`page_size`) because `LocalThreadExecutor` already uses `max_threads`.

**Comment by frsyuki** [comment]
v0.6.20 includes this enhancement. Thank you for your contribution!

**Pull request merged**
