### PR TITLE
Update liquid 4.0.0 again

### LINKED ISSUE #586: Error occur when the embulk data directory beginning with  `+`  char.
Error occur when the embulk data directory beginning with `+` char.
Without  `+`  char, It works well. 

Reported-by [yynozk ](https://twitter.com/yynozk/status/847312648177963008) from twitter Japanese text.

## NG Case

```
git clone https://github.com/yynozk/embulk-error-sample +embulk-error-sample
```

```
+embulk-error-sample
|-- _out.yml.liquid
|-- sample.json
`-- sample.yml.liquid
```

```
embulk run +embulk-error-sample/sample.yml.liquid
2017-03-31 00:44:55.030 +0900: Embulk v0.8.18
org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(org/embulk/config/ModelManager.java:75)
	at org.embulk.config.DataSourceImpl.loadConfig(org/embulk/config/DataSourceImpl.java:220)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:520)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
	at RUBY.run(/Users/user/.embulk/bin/embulk!/embulk/runner.rb:84)
	at RUBY.run(/Users/user/.embulk/bin/embulk!/embulk/command/embulk_run.rb:307)
	at RUBY.<main>(/Users/user/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at Users.user.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(Users/user/$_dot_embulk/bin/embulk/embulk/command/file:/Users/user/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at Users.user.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/Users/user/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
	at org.jruby.Main.internalRun(org/jruby/Main.java:313)
	at org.jruby.Main.run(org/jruby/Main.java:242)
	at org.jruby.Main.main(org/jruby/Main.java:204)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:181)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870)
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:72)
	at org.embulk.config.DataSourceImpl.loadConfig(DataSourceImpl.java:220)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:520)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:389)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:385)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:385)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:850)
	at org.jruby.Ruby.loadFile(Ruby.java:2976)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
	at org.jruby.RubyKernel.require19(RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at Users.user.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/Users/user/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at Users.user.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/Users/user/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.jruby.ir.Compiler$1.load(Compiler.java:111)
	at org.jruby.Ruby.runScript(Ruby.java:834)
	at org.jruby.Ruby.runNormally(Ruby.java:749)
	at org.jruby.Ruby.runNormally(Ruby.java:767)
	at org.jruby.Ruby.runFromMain(Ruby.java:580)
	at org.jruby.Main.doRunFromMain(Main.java:425)
	at org.jruby.Main.internalRun(Main.java:313)
	at org.jruby.Main.run(Main.java:242)
	at org.jruby.Main.main(Main.java:204)
	at org.embulk.cli.Main.main(Main.java:23)

Error: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
 at [Source: N/A; line: -1, column: -1]
 ```

## OK Case

```
git clone https://github.com/yynozk/embulk-error-sample embulk-error-sample
```

```
embulk-error-sample
|-- _out.yml.liquid
|-- sample.json
`-- sample.yml.liquid

0 directories, 3 files
```

```
embulk run embulk-error-sample/sample.yml.liquid
2017-03-31 00:46:13.742 +0900: Embulk v0.8.18
2017-03-31 00:46:27.189 +0900 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'sample.json'
2017-03-31 00:46:27.196 +0900 [INFO] (0001:transaction): Loading files []
2017-03-31 00:46:27.222 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / tasks=0
2017-03-31 00:46:27.241 +0900 [INFO] (main): Committed.
2017-03-31 00:46:27.241 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

### LINKED ISSUE #627: Can't execute embulk with bundle environment
Embulk(0.8.19, and 0.8.20) can't execute if i try to run it with bundle environment

Following exception is presented;
```
bin/embulk mkbundle em2;bin/embulk -b em2 preview conf/foo.yml.liquid
2017-05-15 08:52:31.860 +0300: Embulk v0.8.20
undefined method `line_number' for "in:\n  type: file\n  path_prefix: ":String
    uri:classloader:/liquid/block_body.rb:99:in `block in render'
    org/jruby/RubyArray.java:1734:in `each'
    uri:classloader:/liquid/block_body.rb:75:in `render'
    uri:classloader:/liquid/template.rb:208:in `block in render'
    uri:classloader:/liquid/template.rb:242:in `with_profiling'
    uri:classloader:/liquid/template.rb:207:in `render'
    uri:classloader:/embulk/runner.rb:154:in `run_liquid'
    uri:classloader:/embulk/runner.rb:129:in `read_config'
    uri:classloader:/embulk/runner.rb:32:in `preview'
    uri:classloader:/embulk/command/embulk_run.rb:267:in `run'
    uri:classloader:/embulk/command/embulk_main.rb:2:in `<main>'
    org/jruby/RubyKernel.java:956:in `require'
    file:/Users/kakoni/dev/beans/embulk/bin/embulk!/embulk/command/embulk_bundle.rb:30:in `<main>'

Error: undefined method `line_number' for "in:\n  type: file\n  path_prefix: ":String

```

foo.yml.liquid
```
in:
  type: file
  path_prefix: file.csv
  parser:
    type: csv
    columns:
      - {name: a, type: long}
      - {name: b, type: string}
out:
  type: stdout
```

## Environment
```
ProductName:    Mac OS X
ProductVersion: 10.12.4
BuildVersion:   16E195
```

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
@dmikurube @muga 

Please take a look when you can.

## Summary.

* This PR fix #586 issue. 
* The #586 issue fixed by #587 once. but It occurred regression #627 (See detail #637)
* For fix #627, we needed update JRuby 9.1.11.0 and above.
* The #791 Updated JRuby to 9.1.13.0 (Embulk 0.8.34)
* After update JRuby 9.1.13.0, regression #627 has been fixed.

I checked the following.

1. Fix #586 
2. Does not regression #627 

## 1. Fix #586 Test

This PR Fix #586.

## 1.1 Prepare test

```
git clone https://github.com/yynozk/embulk-error-sample +embulk-error-sample
cd +embulk-error-sample/
```

### 1.2 NG Case (embulk 0.8.34)

```
% embulk run sample.yml.liquid
2017-09-20 20:55:15.297 +0900: Embulk v0.8.34
org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:75)
	at org.embulk.config.DataSourceImpl.loadConfig(DataSourceImpl.java:220)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:536)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:391)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:387)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:387)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:337)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:174)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:467)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:99)
	at org.embulk.cli.Main.main(Main.java:28)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:181)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005)
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:72)
	... 13 more

Error: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
 at [Source: N/A; line: -1, column: -1]
```

### 1.3. Proposed version (Update Liquid 4.0.0)

```
% embulk-0.8.34.jar run sample.yml.liquid
2017-09-20 20:55:49.153 +0900: Embulk v0.8.3X (Update liquid version)
2017-09-20 20:55:54.745 +0900 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'sample.json'
2017-09-20 20:55:54.748 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-09-20 20:55:54.752 +0900 [INFO] (0001:transaction): Loading files [sample.json]
2017-09-20 20:55:54.772 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2017-09-20 20:55:54.781 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
{"id":1,"name":"foo"}
2017-09-20 20:55:54.874 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-09-20 20:55:54.878 +0900 [INFO] (main): Committed.
2017-09-20 20:55:54.879 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"sample.json"},"out":{}}
```

## 2. Regression test

Regression #627 test.

### 2.1 build embulk.gem and startup local rubygems server

```
mkdir -p /tmp/rubygems/gems
cp pkg/embulk-0.8.34.gem /tmp/rubygems/gems
cd /tmp/rubygems
gem generate_index
python3 -m http.server 
```

## 2.2 create mkbundle directory

```
% embulk mkbundle embulk_bundle
2017-09-20 17:08:43.458 +0900: Embulk v0.8.34
Initializing embulk_bundle...
  Creating embulk_bundle/Gemfile
  Creating embulk_bundle/.ruby-version
  Creating embulk_bundle/.bundle/config
  Creating embulk_bundle/embulk/input/example.rb
  Creating embulk_bundle/embulk/output/example.rb
  Creating embulk_bundle/embulk/filter/example.rb
```

```
cd embulk_bundle
vi Gemfile
```

```ruby
source 'https://rubygems.org/'

source 'http://localhost:8000/' do
  gem 'embulk', '~> 0.8.0'
end
```

```
embulk bundle install
2017-09-20 17:10:58.616 +0900: Embulk v0.8.34
Fetching source index from http://localhost:8000/
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 1.10.6
Installing liquid 4.0.0     # <-- Liquid 4.0.0 install
Installing msgpack 1.1.0
Installing rjack-icu 4.54.1.1
Installing embulk 0.8.34
Bundle complete! 1 Gemfile dependency, 5 gems now installed.
Bundled gems are installed into ..
```

```
cd ..
```

`config.yml.liquid`

```
{% include 'test' %}
out: {type: stdout}
```

`_test.yml.liquid`

```
in:
  type: file
  path_prefix: /private/tmp/hoge/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
#out: {type: stdout}
```

### 2.3. embulk run/preview with -b 

```
embulk run -b embulk_bundle config.yml.liquid
2017-09-20 17:12:29.193 +0900: Embulk v0.8.34
2017-09-20 17:12:32.886 +0900 [INFO] (0001:preview): Listing local files at directory '/private/tmp/hoge/csv' filtering filename by prefix 'sample_'
2017-09-20 17:12:32.888 +0900 [INFO] (0001:preview): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-09-20 17:12:32.891 +0900 [INFO] (0001:preview): Loading files [/private/tmp/hoge/csv/sample_01.csv.gz]
2017-09-20 17:12:32.898 +0900 [INFO] (0001:preview): Try to read 32,768 bytes from input source
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```

```
~/OpenProjects/embulk/embulk/pkg/embulk-0.8.34.jar run -b embulk_bundle config.yml.liquid
2017-09-20 17:19:31.115 +0900: Embulk v0.8.34
2017-09-20 17:19:37.480 +0900 [INFO] (0001:transaction): Listing local files at directory '/private/tmp/hoge/csv' filtering filename by prefix 'sample_'
2017-09-20 17:19:37.482 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-09-20 17:19:37.486 +0900 [INFO] (0001:transaction): Loading files [/private/tmp/hoge/csv/sample_01.csv.gz]
2017-09-20 17:19:37.528 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2017-09-20 17:19:37.538 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,Embulk "csv" parser plugin
4,11270,2015-01-29 11:54:36,20150129,
2017-09-20 17:19:37.636 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-09-20 17:19:37.639 +0900 [INFO] (main): Committed.
2017-09-20 17:19:37.640 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/private/tmp/hoge/csv/sample_01.csv.gz"},"out":{}}
```

### CODE REVIEW

**Comment by dmikurube** [comment]
@hiroyuki-sato Let us wait for a while before upgrading Liquid to confirm JRuby 9.1.13.0 is working fine.

**Comment by dmikurube** [comment]
btw, do you have any reasons why you didn't reuse #637?

**Comment by hiroyuki-sato** [comment]
Thanks. Let's wai for a while.

The #637 is Issue, not PR.  Tha's why I don't reuse it.
I don't know how to reuse #637 as PR.

**Comment by dmikurube** [comment]
> The #637 is Issue, not PR. Tha's why I don't reuse it.
Ah, got it. Thanks. They look similar...

**Comment by muga** [comment]
> Let us wait for a while before upgrading Liquid to confirm JRuby 9.1.13.0 is working fine.

Agree. It might be nice to merge this after a week at least.

**Comment by dmikurube** [comment]
Merging this, and will be releasing v0.8.35 in a couple of days...

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
