### PR TITLE
Cleanup parent_first_packages and parent_first_resources as of v0.10.13

### PR DESCRIPTION
**Pull request by dmikurube**
Some dependency libraries have already been moved behind the `DependencyClassLoader`. We no longer need to take care of `parent_first_*` for them.

About `parent_first_*`, see `PluginClassLoader#loadClass`.
https://github.com/embulk/embulk/blob/v0.10.12/embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java#L111

It's a mechanism to prioritize classes on the core side from the plugin's side when duplicated. We plan to remove all the `parent_first_*` mechanism eventually by moving all the dependencies behind `DependencyClassLoader`.

### CODE REVIEW

**Review by himadieievsv — APPROVED** [review]
LGTM

**Review by trung-huynh — APPROVED** [review]

**Comment by dmikurube** [comment]
@trung-huynh @himadieievsv To make #1271 effective for `javax.annotation.*`, I found that these lines need to be removed, too: 6910ddbbe3d1aafc35465df5a0edaa0bae6bbcb7

**Review by himadieievsv — APPROVED** [review]
👍 lgtm

**Comment by dmikurube** [comment]
Thanks! Merging this, and releasing v0.10.13.

**Pull request merged**
