### PR TITLE
Add description field to @Config annotation

### PR DESCRIPTION
**Pull request by xerial**
It would be good if we can add descriptions to `@Config` parameters: 
```
@Config("param", description="parameter description")
```
In future, we can automatically generate documentation of plugin configurations by extracting these annotations.

### CODE REVIEW

**Comment by frsyuki** [comment]
Sounds good idea to have description!
hmm...but "description" is a bit long. Do you think adding description parameter to `@Config` is better than adding `@ConfigDesc` annotation? Because we already have `@ConfigDefault`.

**Comment by xerial** [comment]
Using `desc` instead of `description` is fine. Defining `desc` as a parameter is better than having `@ConfigDesc` since IDE is good at finding `desc` inside `@Config`.

**Comment by frsyuki** [comment]
That's good to know > IDE support.
Isn't it `@Config(value="foo", desc="bar")` by the way? I think we can't omit value= when there're 2 or more parameters.

**Comment by xerial** [comment]
Ah. Yes. This is a little bit annoying. I will consider a better way. Thanks.

**Pull request closed without merging**
