### PR TITLE
added escape,quote and some other options for CSV formatter plugin

### PR DESCRIPTION
**Pull request by sakama**
This PR contains escape,quote and other options for CSV formatter plugin, that I proposed [this Issue](https://github.com/embulk/embulk/issues/168).
  
these option is not contained.

* quote_policy - NONNUMERIC
  I have no idea who need this option.

* skip_empty_lines
  better to use filter plugin.

### CODE REVIEW

**Comment by frsyuki** [comment]
Very Nice! Extraordinary well-written code. I merged.

**Comment by frsyuki** [comment]
Could you check #176?

**Comment by frsyuki** [comment]
And #177?

**Comment by sakama** [comment]
@frsyuki Thank you for merging! Both #176 and #177 seems good :+1:

**Pull request merged**
