### PR TITLE
Add Embulk Logo page for Docs

### PR DESCRIPTION
**Pull request by toru-takahashi**
Add the following page.

Also, #482 is resolved by this PR.

[https://treasure-data.gyazo.com/821862298866a0825577bd29bf0341f4](https://treasure-data.gyazo.com/821862298866a0825577bd29bf0341f4)

[https://treasure-data.gyazo.com/eac84e799e81695304ea52417db26c19](https://treasure-data.gyazo.com/eac84e799e81695304ea52417db26c19)

### CODE REVIEW

**Comment by dmikurube** [comment]
@toru-takahashi Just one question: do you think we should include `.ai` (Adobe Illustrator?) files in the repo?

**Comment by toru-takahashi** [comment]
@dmikurube Fluentd provides .ai file. https://github.com/fluent/fluentd-docs/tree/master/public/logo
So, I followed it.

**Comment by dmikurube** [comment]
@toru-takahashi Got it. Thanks!

I pushed a little bit updated branch https://github.com/embulk/embulk/tree/embulk-logo-v2 to have more consistent filenames and to remove executable attributes.

Please feel free to import that branch in this PR, or let's go ahead as-is and then I'd merge that branch in another PR.

**Comment by toru-takahashi** [comment]
Looks good to me. Please merge it 👍

**Pull request merged**
