### PR TITLE
Translate DecodeLine tests to parametrized test

### PR DESCRIPTION
**Pull request by cosmo0920**
Follow up #299.

I try to convert DecodeLine tests to parametrized test style.
- Add `JUnitParams` dependency and use it for Parametrized test

Question:
- This parametrized tests makes slightly longer test execution time. Is this execution time acceptable?

### CODE REVIEW

**Comment by frsyuki** [comment]
@cosmo0920 Did you have chance to try and evaluate testng?
I would like to have feedback to compare testng vs. junit + JUnitParams.

**Comment by cosmo0920** [comment]
I see. Comparing testng and JUnitParmas is reasonable.
Translate tests with testng in another PR or issue?

But, sadly, I have not enough time until weekend.
Could you wait until weekend?

**Comment by frsyuki** [comment]
> Could you wait until weekend?

Yes, of course.

Current testing structure has following problems:

* Too slow: slow test is bad. this comes from 2 causes:
** Guice and JRuby initialization: initialization of JRuby is taking the longest time. Unless setting `use_global_ruby_runtime` system config, Guice initialization creates a new JRuby instance. And `EmbulkTestRuntime.apply` creates a new Guice Injector for each test case. It means that JRuby initialization runs every time before running a test method. This is too slow. I want to solve this somehow.
** parallel execution: running tests in parallel makes it faster, of course.
* lack of standarized way to write parameterized tests: because embulk is a tool to process data, we often want to iterate tests for different set of data.
* plugin instantiation: to create a new instance of a plugin, we need to get Guice Injector from EmbulkTestRuntime, and get PluginManager from it, and call `newPlugin` method. And to test `transaction` method, create a dummy `Controller` instance to hook TaskSource, then interrupt commit if necessary.

I would like to solve those problems about testing.
TestNG has parallel execution buit-in and some integration with Guice in addition to parametrized test.

**Comment by cosmo0920** [comment]
I'm implementing testNG style parametrized tests in this branch: https://github.com/embulk/embulk/compare/master...cosmo0920:use-testng

**disclaimer**: This branch is working in progress. TestNG tests do not work properly.... :<

**Comment by cosmo0920** [comment]
Or, another plain is using gradle's parallel execution and JUnit experimental Enclosed Runner feature: https://github.com/embulk/embulk/compare/master...cosmo0920:translate-decodeline-tests-to-parametrized-test-with-parallel-fork

This features makes shorten execution test time.

**Comment by cosmo0920** [comment]
Now, we can choose three strategies implementing parametrized tests

1. Use junit-parametrized simply (This PR)
2. Use junit-parametrized and Enclosed runner with gradle parallel execution feature (https://github.com/embulk/embulk/compare/master...cosmo0920:translate-decodeline-tests-to-parametrized-test-with-parallel-fork)
3. Use testng and add testng task which depends on check task (https://github.com/embulk/embulk/compare/master...cosmo0920:use-testng)

**Comment by frsyuki** [comment]
Very good feedback. Please let me take time to check through those code.

**Comment by cosmo0920** [comment]
Yes, of course.

**Comment by dmikurube** [comment]
Sorry that this pull request has been left. It now has a large conflict, and things have been moved. (LineDecoder is now in `embulk-util-text`.)

**Pull request closed without merging**
