### PR TITLE
Remove embedded gems: msgpack, bundler, liquid

### PR DESCRIPTION
**Pull request by dmikurube**
After removing JRuby from Embulk executable binary, it also removes embedded RubyGem libraries: `msgpack`, `bundler`, and `liquid`.

* `msgpack` is mandatory for Ruby-based Embulk plugins. Users would have to install it with `embulk gem install msgpack` by themselves.
* `bundler` has not been mandatory, but some CLI users have used it for maintaining plugin installation. Actually `bundler` is preinstalled in some JRuby versions, so it depends on users which JRuby to use.
* `liquid` has not been mandatory, but some CLI users have used it for templating Embulk configs. JFYI: its's not available for `EmbulkEmbed` users. Users would have to install it with `embulk gem install liquid` by themselves.

### CODE REVIEW

**Review by shroman — APPROVED** [review]
lgtm

**Comment by dmikurube** [comment]
I found that it's not working well, too. Taking a deeper look...

**Comment by dmikurube** [comment]
Ugh, the problem was not just this PR, but my local msgpack gem was too new.

As written in the PR description,
> Users would have to install it with `embulk gem install msgpack` by themselves.

But as of now, Embulk expects `msgpack:1.1.0` although `embulk gem install msgpack` installs the latest `msgpack:1.3.3` automatically. When I installed the specific `msgpack:1.1.0`, I confirmed it worked.

Let me think deeper about it, but I believe we can go ahead with this PR.

**Comment by dmikurube** [comment]
If a user installs `msgpack` just by `embulk gem install msgpack`, `msgpack:1.3.3` is installed as of 2020-11-17, and it does not match `~> 1.1.0`.
https://rubygems.org/gems/msgpack/versions/1.3.3-java

`~>` means that the first digit and the second digit are the same.
https://guides.rubygems.org/patterns/#declaring-dependencies

632ec5647b9d3b0702a792e2966b8fb6c41fcd22 changes the restriction from `~> 1.1.0` to `>= 1.1.0` to keep `embulk-core` work even with newer `msgpack`,

**Comment by dmikurube** [comment]
The PR is ready for review again -- the difference is only 632ec5647b9d3b0702a792e2966b8fb6c41fcd22 .

**Review by shroman — APPROVED** [review]
Looks good, thanks for checking! Looking at the code only doesn't work sometimes :)

**Review by trung-huynh — APPROVED** [review]
LGTM

**Review by himadieievsv — APPROVED** [review]
LGTM

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
