### PR TITLE
Upgrade Apache Maven to 3.9.5

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
I am postponing this change to next v0.11.3, but #1642 would be included.

**Comment by dmikurube** [comment]
After releasing v0.11.2 (with #1642), rebased to the latest `master`.

**Comment by dmikurube** [comment]
Then, merging. (No changes)

**Pull request merged**
