### PR TITLE
Update JRuby to 9.1.1.0 from 9.0.4.0

### PR DESCRIPTION
**Pull request by frsyuki**
JRuby release notes:

* 9.0.5.0: http://jruby.org/2016/01/26/jruby-9-0-5-0.html
* 9.1.0.0: http://jruby.org/2016/05/03/jruby-9-1-0-0.html
* 9.1.1.0: http://jruby.org/2016/05/19/jruby-9-1-1-0.html

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Current embulk use JRUBY 9.0.5.0. So 
Update JRuby to 9.1.1.0 from 9.0.5.0
is better.

```
/pkg/embulk-0.8.9.jar --version
embulk 0.8.9(jruby 9.0.5.0)
```

```diff
diff --git a/lib/embulk/command/embulk_run.rb b/lib/embulk/command/embulk_run.rb
index dd2bc86..5a5bcc1 100644
--- a/lib/embulk/command/embulk_run.rb
+++ b/lib/embulk/command/embulk_run.rb
@@ -15,7 +15,7 @@ module Embulk
     i = argv.find_index {|arg| arg !~ /^\-/ }
     unless i
       if argv.include?('--version')
-        puts "embulk #{Embulk::VERSION}"
+        puts "embulk #{Embulk::VERSION}(jruby #{JRUBY_VERSION})"
         system_exit_success
       end
       usage nil
```

**Comment by muga** [comment]
I'm interested in JRuby 9.1.0.0 or later because of https://github.com/jruby/jruby/issues/3660

**Comment by muga** [comment]
And also identified the plugin installation failure caused by https://github.com/jruby/jruby/issues/3635

**Comment by sonots** [comment]
I am also interested in JRuby 9.1.0.0 because jruby 9.0.5.0 has this issue > https://github.com/embulk/embulk-output-bigquery/issues/38

**Comment by hakobera** [comment]
Latest release of jruby is 9.1.2.0 http://jruby.org/2016/05/27/jruby-9-1-2-0.html

It's include bugfix of 9.1.1.0, so I think update to 9.1.2.0 is better now.

**Comment by frsyuki** [comment]
updated to 9.1.2.0.

**Pull request merged**
