### PR TITLE
Enable dependency locking for executable binary distributions

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

Minor comment.
I'm not familiar the dependency locking. The description of the difference `embed` and `depsEmbedded` is useful for me. Could you write a short description?

This PR create four lockfiles(compileClasspath.lockfile, depsEmbedded.lockfile, pluginEmbedded.lockfile and runtimeClasspath.lockfile), resolve library dependency and embed **specific** version jar into embulk package. Correct?

**Comment by dmikurube** [comment]
Thanks!

> I'm not familiar the dependency locking. The description of the difference embed and depsEmbedded is useful for me. Could you write a short description?

Sounds good. Added some comments in: 2c558fa7b17069c76f652695e514eee8ae3e3f7c


> This PR create four lockfiles(compileClasspath.lockfile, depsEmbedded.lockfile, pluginEmbedded.lockfile and runtimeClasspath.lockfile), resolve library dependency and embed **specific** version jar into embulk package. Correct?

`compileClasspath` and `runtimeClasspath` are the same with other util libraries and plugins. They are used as normal librarires.

`depsEmbedded` and `pluginEmbedded` are contained like `/lib/(something).jar` in the final executable Embulk distribution binary (like `embulk-0.10.45.jar`). They are loaded by a sub classloader, not the top-level Java application classloader, so that they are not visible from plugins.

You may want to try `unzip -l embulk-0.10.44.jar` to see what are included.

**Comment by dmikurube** [comment]
Anyway, merging...

**Comment by hiroyuki-sato** [comment]
Thank you for your comment!

**Pull request merged**
