### PR TITLE
Checkstyle the entire project with modified Google's Java Style Guide

### PR DESCRIPTION
**Pull request by dmikurube**
Nothing has been accepted nor determined yet, but just suggesting to apply checkstyle, and to change the coding style...

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Will you change coding style Airlift to Google style?
(I'm not sure what is difference)

Current plugin coding style based on this file
https://github.com/airlift/codestyle/blob/master/IntelliJIdea14/Airlift.xml

Ref: [Embulkのソースコードスタイルチェック方法 (Java編)](http://qiita.com/hiroysato/items/584eafb4a94a961fa571)

**Comment by dmikurube** [comment]
@hiroyuki-sato As mentioned, nothing has been accepted nor determined. Just remembered some of us talked about this, and I just tried. We'd want to have checkstyle in the Embulk core for some coding styles, anyway. (The core does not have checkstyle, for the time being!)

Coding styles are totally up to each plugin. This does not have any impacts on plugins. It is for the core source code, not for plugins.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for the comment.

IMO

* It is a good idea to add automated code style setting into core. 
* And also, it is a good idea to use same coding style (core and **template**).

These are just past story, not related to future.

A user asked the original author about coding style. 
And it was Airlift. So I requested to add code style template for a plugin #361.
(Maybe, I was also better to try it into core at the same time)

And many users didn't know much about Airlift. 
(It was(still current) minor style.) :smile:

**Comment by dmikurube** [comment]
> And also, it is a good idea to use same coding style (core and template).

We don't think they always need to be the same. For example, one idea is to provide options in `embulk new` to specify coding styles. (Maintaining multiple versions are annoying, though. It's an extreme viewpoint. ;) )

**Comment by hiroyuki-sato** [comment]
> For example, one idea is to provide options in embulk new to specify coding styles. 

It's a nice idea!

I want to know recommend code style. (ex: default style).
I can't select it. :sweat_smile:

**Comment by dmikurube** [comment]
I believe we don't have recommendations unless the plugin is merged into embulk-standards/. Options for auto-generation would be limited, though. It's totally up to plugin developers. :)

**Comment by hiroyuki-sato** [comment]
The recommendation mean that If the core use "Airlift", I will use it for a plugin.
If the core uses another coding style, I'll use it for a plugin too. 

I don't have any policy about code style. I want to use the same code style. :smile:

Ref: [Twitter](https://twitter.com/hanpen_good/status/623266724763140096) (Japanese)

**Comment by muga** [comment]
This is my thoughts.
1. The current Embulk doesn't have strict coding style. That's bad thing. Strictly speaking, we started development of Embulk by using "Airlift" coding style implicitly. But, some parts are applied and others are not applied. That's a biggest issue.
2. I thought that it's good to use same style as both of Embulk and Java plugins first but, now I think that we should not force plugin developers to use the style. Also think that the checkstyle.xml should be removed from build.gradle generated by `embulk new` command. 
3. Since the change diff is small instead of "Google" if we would take "Airlift" style, I prefer "Airlift". I don't have any other reasons that I advocate it but.
4. But, I'm OK to change the style from "Airlift" to "Google". Not big issue. Rather, #1 is big problem.

**Comment by hiroyuki-sato** [comment]
If the `checkstyle.xml` remove from the `gradle new` command,
Some documents may helpful for new plugin developer. 

I just want to use the same coding style.

## The Embulk coding style.

Write a description; It is not important to use the same coding style.
But If you want to use the same coding style, please refer the following. 

* For IntelliJ (URL here)
* For gradle (XML file link here), example the following.

### checkstyle example.

```
plugins {
    // java
    id "checkstyle"
}

checkstyle {
  // ... 
}
```

**Comment by dmikurube** [comment]
This ticket/PR does not care about plugins anyway.

IMHO, the coding style of the core does not represent any recommendation. Although it's free for plugin developers to follow the coding style of the code, the core does not (should not) take care.

Although it's worth discussing how `embulk new` should work, it's to be done in a separate ticket if needed.

**Comment by dmikurube** [comment]
It's not urgent. It's not a topic to spend much time to discuss. Let's avoid bikeshed.

Topics to discuss here in this ticket are only:

1. Should we introduce `checkstyle` for the core code base?
2. If yes for 1, which style to introduce for the core code base?

* Plugins are out of focus. It's to be discussed per plugin.
* `embulk new` is out of focus of this ticket. It's to be discussed in another ticket.

**Comment by hiroyuki-sato** [comment]
Sorry for the writing much about outside of the main topic. 
I have no opinion about the main topic.
I know a little about the ​Airlift style only.

**Comment by muga** [comment]
@dmikurube  Thank you for simplifying.

For 1, it's better to introduce checkstyle to perform code quality. But, I also think that it's good to postpone to do that for now, if we need to discuss for 2 more:-) 

For 2, I prefer "Airlift" because the diff is small if we would take "Airlift" style instead. But, I don't have any other reasons that I advocate it.

**Comment by dmikurube** [comment]
My opinions:

1. Yeah, we should have "some".
2. I thought Google's + following modifications may fit Embulk well:
    * Indent: 2 ==> 4
    * Columns: 100 ==> 120 or more
    * Package names: allow `_`

The reasons of 2 are:

* As mentioned, the "Airlift" style is not very popular. :( To make Embulk more friendly for open-source developers, we may want to use more popular ones.
* Updating all existing indents is hard, and breaks all Git histories. Keeping 4 is reasonable.
* 100 columns are too short for 4-space indents.

----

Once we introduce some stylechecks, we anyway need to update existing code eventually. I'd suggest to utilize suppressions to update the existing code gradually. 

* Add checkstyles with all existing Java files suppressed.
* Remove good files from suppressions.
* Do not add new Java files in suppressions.
* Update existing Java files with cleaning-up and removing from suppressions when we have chances.

This process can be easily applied even for Airlift's and Google's.

**Comment by dmikurube** [comment]
@muga @sakama Adding checkstyle, finally. Can you have a look?

This PR does not check any file for the time being. Next #914 will enable checkstyle for embulk-core's main files.

**Comment by dmikurube** [comment]
Thanks... Merging, finally!

**Pull request merged**
