### PR TITLE
Move FilterPlugin, FormatterPlugin, InputPlugin, OutputPlugin, and ParserPlugin to embulk-spi

### PR DESCRIPTION
**Pull request by dmikurube**
After `Page` and related classes were moved to `embulk-api` in #1277, #1285, #1286, and so on, five remaining plugin classes `FilterPlugin`, `FormatterPlugin`, `InputPlugin`, `OutputPlugin`, and `ParserPlugin` are now ready to move to `embulk-spi`.

This PR moves them, add Javadoc and license boilerplates.

### CODE REVIEW

**Review by himadieievsv — APPROVED** [review]
LGTM

**Review by shroman — APPROVED** [review]
lgtm

**Comment by dmikurube** [comment]
Thanks!

**Comment by dmikurube** [comment]
Its `base` didn't catch up with `master`. Then, merged manually at: 69a8f420ad9b4aaa24f1e1719f66533c2662c925

**Pull request merged**
