### PR TITLE
Relax deprecation messages of TimestampFormatter/Parser constructors: #768

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Can you have a look? This is trying to relax: #768

Cc: @hiroyuki-sato @hito4t

### CODE REVIEW

**Comment by dmikurube** [comment]
@hiroyuki-sato Technically possible at a whole, but difficult once per plugin. I thought it may confuse users and developers.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thanks. LGTM

**Comment by hito4t** [comment]
Great!
Thank you!

**Comment by dmikurube** [comment]
Thanks, all! Merging.

I think to release a new version (v0.8.31) just with this PR to provide a stable version with shorter deprecation messages.

**Pull request merged**
