### PR TITLE
CsvParserPlugin accepts more values as true

### PR DESCRIPTION
**Pull request by frsyuki**
This change makes CsvParserPlugin more flexible.

### CODE REVIEW

**Comment by frsyuki** [comment]
@muga can you review this change?

**Comment by muga** [comment]
LGTM

**Comment by muga** [comment]
I added import statement: https://github.com/embulk/embulk/commit/084d13f57ebe4979066eff0584511d6c4006a84d

**Comment by frsyuki** [comment]
:+1:

**Pull request merged**
