### PR TITLE
Upgrade jruby-gradle-jar-plugin to 1.5.0.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Can you have a look? It may solve the problem of the "rubygems.lasagna.io" problem in building Embulk. (Thanks to @hiroyuki-sato's finding. :) )

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@muga @dmikurube 
JFYI https://github.com/jruby-gradle/jruby-gradle-plugin/issues/297

**Comment by muga** [comment]
Let me check diff https://github.com/jruby-gradle/jruby-gradle-plugin/compare/v1.0.1...v1.5.0

**Comment by hiroyuki-sato** [comment]
@muga https://github.com/jruby-gradle/jruby-gradle-plugin/commit/2d1c14e1765f666a70fb90484486ee17290f5093 maybe this commit.

**Comment by muga** [comment]
@hiroyuki-sato cool. thank you.

**Comment by muga** [comment]
@dmikurube @hiroyuki-sato It seems that jruby-gradle-plugin is built by Java8 and the class files are formatted in version 52.0. If we use the plugin v1.5.0, we might not be able to build Embulk by Java7. To use v1.5.0, do we build Embulk by Java8? Or we will look for other workarounds?

https://github.com/jruby-gradle/jruby-gradle-plugin/compare/v1.0.1...v1.5.0#diff-c197962302397baf3a4cc36463dce5eaR21

To test Embulk on Travis CI, we already use Java8. That is the reason why this PR's build passed.
https://github.com/embulk/embulk/blob/master/.travis.yml#L3

**Comment by hiroyuki-sato** [comment]
Maybe we need update jruby-gradle again when rubygems.lasagna.io back.
https://github.com/jruby-gradle/jruby-gradle-plugin/issues/297#issuecomment-320670502

**Comment by hiroyuki-sato** [comment]
@dmikurube @dmikurube 
Ah, Java8.....
It found temporary fix 
https://github.com/jruby-gradle/jruby-gradle-plugin/issues/297#issue-248368105

But I'm not sure where is add this entry in Embulk.

And also I asked `rubygems.lasagna.io` status.
https://github.com/jruby-gradle/jruby-gradle-plugin/issues/297#issuecomment-326155030

**Comment by dmikurube** [comment]
Maybe the top one (in `buildscript { ... }`) would work. Will try that later.

**Comment by dmikurube** [comment]
@muga @hiroyuki-sato Trying #776.

**Comment by dmikurube** [comment]
#776 looks successful. I keep this PR open, and will merge when we go Java 8.

**Comment by dmikurube** [comment]
@sakama (Cc: @muga) Embulk is going to Java 8 after #853, and ready for this PR. Can you have a look?

**Comment by dmikurube** [comment]
Thanks! Merging.

**Pull request merged**
