### PR TITLE
Update build.gradle and remove pom.xml and update

### LINKED ISSUE #39: Remove pom.xml
Once bulid.grade file gets stabled, we don't need pom.xml any more.
Delete pom.xml and update README.md.

### PR DESCRIPTION
**Pull request by frsyuki**
This updates build.gradle so that we can use almost all work using gradle.
See changes of README.md for usage.

Fixes #39.

### CODE REVIEW

**Comment by frsyuki** [comment]
#44 is also fixed.

**Comment by frsyuki** [comment]
@muga @nahi build commands are changed. Please check README.md/

**Comment by muga** [comment]
:+1:

**Comment by muga** [comment]
@frsyuki I noticed that ./pom.xml and ./embulk-standards/pom.xml exist. Can I remove them?

**Comment by frsyuki** [comment]
Good point. I removed them.

**Pull request merged**
