### PR TITLE
Un-JRuby the "selfupdate" subcommand.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Trying to convert `selfupdate`. It's upon #560 which is converting Embulk::VERSION to Java.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
In short, LGTM.

## prepare

### checkout java-embulk-version branch for test.

```
% git checkout -b selfupdate_test
Switched to a new branch 'selfupdate_test'
hsato-mbp13:embulk hsato$ git log | head
commit 8f17cedbe3e55f98875850735871ddd34cc3d5b9
Author: Dai MIKURUBE <dmikurube@treasure-data.com>
Date:   Wed Apr 5 12:45:57 2017 +0900

    Revert embulk.gemspec so that embulk.gem works.

commit 896b9cb6f55b1f77b70f28ca849ac1d6b63c5432
Author: Dai MIKURUBE <dmikurube@treasure-data.com>
Date:   Tue Apr 4 15:34:14 2017 +0900
```

### merge java-embulk-selfupdate for test.

```
git merge --ff upstream/java-embulk-selfupdate
Removing lib/embulk/command/embulk_selfupdate.rb
Merge made by the 'recursive' strategy.
 embulk-cli/build.gradle                                       |   1 +
 embulk-cli/src/main/java/org/embulk/cli/EmbulkSelfUpdate.java | 260 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 lib/embulk/command/embulk_run.rb                              |   4 +-
 lib/embulk/command/embulk_selfupdate.rb                       | 122 -------------------------------------------------
 4 files changed, 262 insertions(+), 125 deletions(-)
 create mode 100644 embulk-cli/src/main/java/org/embulk/cli/EmbulkSelfUpdate.java
 delete mode 100644 lib/embulk/command/embulk_selfupdate.rb
```

### force version down to 0.8.17

```diff
diff --git a/build.gradle b/build.gradle
index 1504361e..ff33a1c4 100644
--- a/build.gradle
+++ b/build.gradle
@@ -16,7 +16,7 @@ def release_projects = [project(":embulk-core"), project(":embulk-standards"), p

 allprojects {
     group = 'org.embulk'
-    version = '0.8.18'
+    version = '0.8.17'

     ext {
         jrubyVersion = '9.1.5.0'
```

### build binary.

```
./gradlew cli
```

### check

```
./pkg/embulk-0.8.17.jar -version
Embulk v0.8.17
```

## update test

* Expect: `embulk selfupdate` update embulk-0.8.17.jar version to 0.8.18.
* Result: updated to 0.8.18

```
./pkg/embulk-0.8.17.jar selfupdate
2017-04-05 17:08:54.182 +0900: Embulk v0.8.17
Checking the latest version...
Found a newer version 0.8.18.
Downloading https://dl.bintray.com/embulk/maven/embulk-0.8.18.jar ...
Failed to load version.properties. Skipping.
Updated to 0.8.18.
```


```
./pkg/embulk-0.8.17.jar -version
Embulk v0.8.18
```

## downgrade test

* Expect: `embulk selfupdate` downgrade embulk-0.8.17.jar version to 0.8.16.
* Result: updated to 0.8.16

```
gradlew ./cli
```

```
./pkg/embulk-0.8.17.jar selfupdate 0.8.16
2017-04-05 17:10:09.877 +0900: Embulk v0.8.17
Checking version 0.8.16...
Found version 0.8.16.
Downloading https://dl.bintray.com/embulk/maven/embulk-0.8.16.jar ...
Failed to load version.properties. Skipping.
Updated to 0.8.16.
```

```
./pkg/embulk-0.8.17.jar -version
Embulk v0.8.16
```

**Comment by dmikurube** [comment]
@muga Updated this PR with rebasing to catch up with the latest `master` for Java-based VERSION. The main logic does not change.

**Comment by dmikurube** [comment]
@muga Updated to catch up with #597. The difference is only in `getJarVersion` to get the version from the jar manifest.

This PR can be merged now independently from other PRs, such as #597.

**Comment by dmikurube** [comment]
Rebased 37d093686c4653512d1c01e4d012112f47a464dd onto `master` as 37d093686c4653512d1c01e4d012112f47a464dd so as to resolve the embulk-cli/build.gradle conflict.

**Comment by dmikurube** [comment]
Merging this.

**Pull request merged**
