### PR TITLE
Modernize embulk-encoder-gzip with v0.11-ready API/SPI

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by dmikurube** [comment]
`embulk-util-file` will be updated to `0.1.2` in another PR after this is merged to `master`. (#1410 needed to be on this branch to use `0.1.2`, but this PR was developed before #1410. Rebasing everything would be hard...)

**Comment by dmikurube** [comment]
`embulk-util-file:0.1.3` would work. Updated.

**Review by huylenq — APPROVED** [review]
LGTM

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
