### PR TITLE
Add "sec_fraction" (fraction part) to "seconds" (epoch second) in parsing timestamps: Fix #1033

### LINKED ISSUE #1033: Embulk v0.9.7 can't parse milliseconds part in `%s.%N` and `%s.%L` format.
Reported by [ntrgiang](https://github.com/embulk/embulk/issues/467#issuecomment-416636390)

Embulk v0.9.7 can't parse milliseconds part in `%s.%N` and `%s.%L` format.
Embulk v0.8.39 can parse it. 

[Reporduce code](https://github.com/hiroyuki-sato/embulk-support/tree/master/core_467_timestamp_format/ntrgiang)

```
2018-08-29 19:05:16.852 +0900: Embulk v0.8.39
+-----------------+-----------------------------+------------+-------------+
| key_name:string |               day:timestamp | value:long | name:string |
+-----------------+-----------------------------+------------+-------------+
|   2 new_clients | 2018-04-06 11:06:02.001 UTC |          1 |           a |
|   3 new_clients | 2018-04-06 11:06:03.001 UTC |          2 |           b |
|   4 new_clients | 2018-04-06 11:06:04.001 UTC |          3 |           c |
+-----------------+-----------------------------+------------+-------------+
```

```
2018-08-29 19:05:50.172 +0900: Embulk v0.9.7
+-----------------+-------------------------+------------+-------------+
| key_name:string |           day:timestamp | value:long | name:string |
+-----------------+-------------------------+------------+-------------+
|   2 new_clients | 2018-04-06 11:06:02 UTC |          1 |           a |
|   3 new_clients | 2018-04-06 11:06:03 UTC |          2 |           b |
|   4 new_clients | 2018-04-06 11:06:04 UTC |          3 |           c |
+-----------------+-------------------------+------------+-------------+
```

### PR DESCRIPTION
**Pull request by dmikurube**
Details are discussed in #1033.

Can you have a look? @sakama @kamatama41 Cc: @hiroyuki-sato

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @dmikurube 

Thank for fixing an issue.

The test-scripts worked well. Thank you!.

[example](https://github.com/hiroyuki-sato/embulk-support/tree/master/core_467_timestamp_format/ntrgiang)

```
embulk-0.9.8-SNAPSHOT.jar preview conf.yml
2018-09-11 15:32:58.061 +0900: Embulk v0.9.8-SNAPSHOT
+-----------------+-----------------------------+------------+-------------+
| key_name:string |               day:timestamp | value:long | name:string |
+-----------------+-----------------------------+------------+-------------+
|   2 new_clients | 2018-04-06 11:06:02.001 UTC |          1 |           a |
|   3 new_clients | 2018-04-06 11:06:03.001 UTC |          2 |           b |
|   4 new_clients | 2018-04-06 11:06:04.001 UTC |          3 |           c |
+-----------------+-----------------------------+------------+-------------+
```

**Comment by dmikurube** [comment]
Rebased from e43ed7db3c0ac72c68bc58197e2c90dede137740 to fix typo in the commit message, and then fixed cases of negative epoch seconds. Jfyi: @kamatama41

**Comment by dmikurube** [comment]
Thanks!

**Comment by ntrgiang** [comment]
big thanks to the team!

**Pull request merged**
