### PR TITLE
[Doc] Add newline for item lists.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Fix indent

http://www.embulk.org/docs/developers/index.html#design-docs-for-core-developers

Current results.

```
Summary * Un-JRuby in the boot process * [TBD] Update plugin loading: non-Gem plugins, namespaces, and versions * [TBD] Un-JRuby in the plugin load process * [TBD] Provide better OAuth support in plugins * [TBD] Buffer in output plugins * [TBD] Structure documents: configs and errors * [TBD] Deliver errors and notifications more flexibly
```

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@dmikurube Please take a look.

**Comment by hiroyuki-sato** [comment]
Hummm... I double checked this issue. The PR #577 fixed this and render correctly in my environment.
It seems something wrong. 

BTW
I don't have any permission on the Embulk repo. So I can't merge it. :smile:

**Comment by dmikurube** [comment]
Got it. It may not be pushed into embulk.org yet. Let's wait. I'd confirm.

**Comment by dmikurube** [comment]
Hmm, documents look compiled well when #577 was merged, and the existing #577 compiled well to a list also in my environment, but embulk.org's one is still strange. Let's try merging this.

**Comment by dmikurube** [comment]
Does not change... http://www.embulk.org/docs/developers/index.html

**Comment by hiroyuki-sato** [comment]
OMG.

I found the following warning about this document. 
I'm not sure the relation with this issue. 

```
checking consistency... /path/to/embulk/embulk-docs/src/developers/index.rst:: WARNING: document isn't included in any toctree
done
```

**Comment by dmikurube** [comment]
For got to see https://github.com/embulk/embulk.github.io. The repo is not updated.

Will have a look later..., but that warning may be related. Thanks for contribution!

**Pull request merged**
