### PR TITLE
Add MavenPluginType with ignoring MavenPluginType in InjectedPluginSource and JRubyPluginSource

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by dmikurube** [comment]
Split from #666. Needs updating the base of this PR before merging.

**Comment by muga** [comment]
#666 looks good to me. Please let me know if this PR is ready to review.

**Comment by dmikurube** [comment]
@muga It's ready now.

In addition to #666, it changes how to tell whether a `PluginType` is `Default-` or `Maven-`. `PluginSource.Type` is newly introduced to identify `PluginType` with that.

The `source` entry will correspond to `PluginSource`:
* `default` ==> `InjectedPluginSource` or `JRubyPluginSource`
* `maven` ==> `MavenPluginSource` (not implemented)

**Comment by muga** [comment]
ok- I start taking a look.

**Comment by dmikurube** [comment]
0.8.24 has been released. Merging this for 0.8.25.

**Pull request merged**
