### PR TITLE
Cleanup build.gradle

### PR DESCRIPTION
**Pull request by dmikurube**
The build scripts (`build.gradle`) in the repository have been chaotic. It was partially because of the `bintray` Gradle plugin, but we now dropped JCenter/Bintray (#1401). It's time to cleanup `build.gradle` in the repository!

To be easier to review/trace, and not to make mistakes, this pull request consists of several Git commits for step-by-step changes.

### CODE REVIEW

**Review by shroman — APPROVED** [review]
lgtm

**Review by trung-huynh — APPROVED** [review]
LGTM

**Comment by dmikurube** [comment]
Thanks!

**Comment by dmikurube** [comment]
Resolved merge conflict -- `master` has been `0.10.29-SNAPSHOT` while this branch has been expecting `0.10.28-SNAPSHOT`.

**Pull request merged**
