### PR TITLE
[RFC/WIP] ExecSession.getTransactionUniqueName

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
I roughly implement `ExecSession.getTransactionUniqueName`
How do you think this idea?

This issue may solve #529.

First I read [this comment](https://github.com/embulk/embulk/issues/529#issuecomment-274415533) and I knew it's embulk-output-td issue.
Today I read this line.
Oh!, It needs `ExecSession.getTransactionUniqueName()` method.
That's why I implement it.

It returns a random session string like `20170519_053301_000000000_mrh0tkfs45tp5`. 
(Maybe, I don't how to test this code yet)
This is temporary implementation. Because if we update Java8, we can use nanosec. 

https://github.com/treasure-data/embulk-output-td/blob/master/src/main/java/org/embulk/output/td/TdOutputPlugin.java#L576

```java
  Timestamp time = exec.getTransactionTime(); // TODO implement Exec.getTransactionUniqueName()
  return String.format("embulk_%s_%09d",
          DateTimeFormat.forPattern("yyyyMMdd_HHmmss").withZoneUTC().print(time.getEpochSecond() * 1000),
          time.getNano());
```

Ref:  [Twitter](https://twitter.com/nora96o/status/865121937248223232)

### CODE REVIEW

**Comment by muga** [comment]
@hiroyuki-sato Thank you for investigating and suggesting. 

It seems, the root cause of the problem is that embulk-output-td's session names are duplicated so, I think that embulk-output-td should fix this issue by using random string that you mentioned or UUID or something.

**Comment by hiroyuki-sato** [comment]
@muga Thank you for your comment. 

Here is my understanding. Is this correct?. If so, I'll close this issue.

* The core doesn't provide `ExecSession.getTransactionUniqueName` at this time. 
* If we update to Java8, we can use nanoseconds time. The`ExecSession.getTransactionTime` return high precision time.

**Comment by muga** [comment]
@hiroyuki-sato Personally it's good to support `unique_transaction_name` in Embulk and embulk-output-td uses the unique name as bulk_import session name but, Embulk doesn't suport the parameter for now. So, I'll try to fix it in embulk-output-td as workaround.

I also think that it's good to pass the value from an external tool to Embulk like workflow or something personally. We need to discuss about the design but.

**Comment by hiroyuki-sato** [comment]
@muga 
Thank you for your comment. 
I just wanted to ask your opinion for future development.

**Pull request closed without merging**
